language: c

addons:
  apt:
    update: true
  homebrew:
    update: true

matrix:
  include:
    - os: linux
      dist: trusty
      env: DEFINITION=5.2.17
    - os: linux
      dist: trusty
      env: DEFINITION=5.3.29
    - os: linux
      dist: trusty
      env: DEFINITION=5.4.45
    - os: linux
      dist: trusty
      env: DEFINITION=5.5.38
    - os: linux
      dist: trusty
      env: DEFINITION=5.6.40
    - os: linux
      dist: trusty
      env: DEFINITION=7.0.33
    - os: linux
      dist: trusty
      env: DEFINITION=7.1.33
    - os: linux
      dist: xenial
      env: DEFINITION=7.2.33
    - os: linux
      dist: xenial
      env: DEFINITION=7.3.22
    - os: linux
      dist: xenial
      env: DEFINITION=7.4.10
    - os: linux
      dist: xenial
      env: DEFINITION=8.0snapshot
    - os: osx
      osx_image: xcode10.1
      env: DEFINITION=5.5.38
    - os: osx
      osx_image: xcode10.1
      env: DEFINITION=5.6.40
    - os: osx
      osx_image: xcode11.3
      env: DEFINITION=7.0.33
    - os: osx
      osx_image: xcode11.3
      env: DEFINITION=7.1.33
    - os: osx
      osx_image: xcode11.3
      env: DEFINITION=7.2.33
    - os: osx
      osx_image: xcode11.3
      env: DEFINITION=7.3.22
    - os: osx
      osx_image: xcode11.3
      env: DEFINITION=7.4.10
    - os: osx
      osx_image: xcode11.3
      env: DEFINITION=8.0snapshot

before_install:
  - export PHP_BUILD_EXTRA_MAKE_ARGUMENTS="-j2"
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if [[ "$DEFINITION" =~ ^("5.2.".*)$ ]]; then
            export PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
        fi
        if [[ "$DEFINITION" =~ ^("7.3.".*)$ ]]; then
            export PHP_BUILD_CONFIGURE_OPTS="--without-libzip"
        fi
        if [[ "$DEFINITION" =~ ^("7.4.".*)$ ]]; then
            set -xe \
              && mkdir -p /tmp/oniguruma \
              && cd /tmp/oniguruma \
              && curl -Ls https://github.com/kkos/oniguruma/releases/download/v6.9.4/onig-6.9.4.tar.gz \
                | tar xzC /tmp/oniguruma --strip-components=1 \
              && ./configure --prefix=/usr/local \
              && make -j $(nproc) \
              && sudo make install \
              && cd $TRAVIS_BUILD_DIR
        fi
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        if [[ "$DEFINITION" =~ ^("5.".*)$ ]]; then
            ./build-openssl-1.0.sh
            export PHP_BUILD_CONFIGURE_OPTS="$PHP_BUILD_CONFIGURE_OPTS --with-openssl=/usr/local/opt/openssl@1.0"
        fi
        if [[ "$DEFINITION" =~ ^("8.0".*)$ ]]; then
            brew install bison
            export PATH="/usr/local/opt/openssl@1.1/bin:/usr/local/opt/bison/bin:$PATH"
            export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/bison/lib"
        fi
    fi
install:
  - ./install-dependencies.sh
  - git clone https://github.com/sstephenson/bats
  - bats/install.sh $HOME
  - export PATH=$HOME/bin:$HOME/libexec:$PATH
  - bats --version

script:
  - ./run-tests.sh $DEFINITION

after_failure:
  - head -1000 $(ls -r /tmp/php-build*.log | head -n 1)
