name: ci
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - 'centos:8'
          - 'ubuntu:20.04'
        php:
          - '5.2.17'
          - '5.3.29'
          - '5.4.45'
          - '5.5.38'
          - '5.6.40'
          - '7.0.33'
          - '7.1.33'
          - '7.2.33'
          - '7.3.21'
          - '7.4.9'
        exclude:
          - { distro: 'centos:8', php: '5.2.17'}
          - { distro: 'centos:8', php: '5.3.29'}
          - { distro: 'centos:8', php: '5.4.45'}
          - { distro: 'centos:8', php: '5.5.38'} #FIXME: openssl 1.1.0
          - { distro: 'ubuntu:20.04', php: '5.2.17'}
          - { distro: 'ubuntu:20.04', php: '5.3.29'}
          - { distro: 'ubuntu:20.04', php: '5.4.45'}
          - { distro: 'ubuntu:20.04', php: '5.5.38'}
          - { distro: 'ubuntu:20.04', php: '5.6.40'} #FIXME: curl-config
        include:
          - { distro: 'ubuntu:16.04', php: '5.3.29', openssl102: true}
          - { distro: 'ubuntu:16.04', php: '5.4.45', openssl102: true}
          - { distro: 'ubuntu:16.04', php: '5.5.38', openssl102: true}
          - { distro: 'ubuntu:18.04', php: '5.6.40'}
    name: "test (php-${{ matrix.php }}, ${{ matrix.distro }})"
    container: "${{ matrix.distro }}"
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          set -ex
          ./install-dependencies.sh
          git clone --depth 1 https://github.com/sstephenson/bats.git
          ./bats/install.sh /usr/local
          if [ "${{ matrix.openssl102 }}" = "true" ]; then
            ./build-openssl-1.0.sh
          fi
      - name: run tests
        run: |
          set -ex
          if [ "${{ matrix.openssl102 }}" = "true" ]; then
            export PHP_BUILD_CONFIGURE_OPTS="$PHP_BUILD_CONFIGURE_OPTS --with-openssl=/usr/local/opt/openssl@1.0"
          fi
          ./run-tests.sh ${{ matrix.php }}
